### ISSUE TITLE
Undefined offset: 0 while running the script.

### ISSUE THREAD

**Issue by HSBSINGH** [rogergerecke/SwissEphemeris#12]
Hi,
I was trying to run script on local windows machine with XAMPP Version: 7.3.10
. While running following errors are coming, if you don't mind can you guide how to overcome this.

Notice: Undefined offset: 0 in D:\Projects\xampp\htdocs\Astrology\SwissEphemeris-master\src\SwissEphemeris\SwissEphemeris.php on line 718

Notice: Undefined offset: 0 in D:\Projects\xampp\htdocs\Astrology\SwissEphemeris-master\src\SwissEphemeris\SwissEphemeris.php on line 719
Array ( ) 

Thank you.

**Comment by rogergerecke** [comment]
ok i have local the same error on production linux server works???   I update the repro with throw messages  the execute command return local a empty array at this time i dosnt now the problem

**Comment by rogergerecke** [comment]
any idea

**Comment by rogergerecke** [comment]
win power shell problem???

**Comment by rogergerecke** [comment]
ok really i think the problem is php send the query to the windows cmd.exe  so in a docker container with linux or on production linux its work in the moment i have no a god solution

**Comment by rogergerecke** [comment]
Ok i worke on this problem @HSBSINGH

**Comment by rogergerecke** [comment]
add windows 10 support @HSBSINGH
